### ISSUE TITLE
Consider raising minimum deployment target due to small impact on app launch time

### ISSUE THREAD

**Issue by insidegui** [b3ll/Decomposed#2]
I was profiling my app's launch times with Instruments and was surprised to see in the "Static Initializer Calls" instrument an `installGetClassHook_untrusted()` call taking up some of the app's launch time. Upon inspecting where in the app this call was originating from, I noticed that it was in one of my framework targets, the only one that links against Decomposed.

Doing some research, it looks like this call gets added for supporting Swift compiled with more recent versions of the compiler when running on older versions of the OS. My app's deployment target is iOS 15, but Decomposed seems to support all the way back to iOS 10.

[According to this thread](https://forums.swift.org/t/performance-of-installgetclasshook-untrusted-at-startup/41636) in the Swift forums, if the deployment target is set to iOS 13 or later, then this call doesn't get injected.

Not sure if you'd be willing to raise the deployment target to address this, but wanted to note in case anyone else googles that symbol name :)

For now I'm using a fork where I've changed the deployment target to iOS 15 / macOS 12, which is what I need for my app.

Thanks for the amazing work!

**Comment by b3ll** [comment]
wow, really great catch! I'll double check 13 is also the min for Motion, since that just makes sense at this point.

I'll bump the deployment target when I get a sec
